// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lswsqoiocrflpmcsmjel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzd3Nxb2lvY3JmbHBtY3NtamVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4MTA3MzUsImV4cCI6MjA4NTM4NjczNX0.Mq4wacSmiKiF8aSCpI-lwrdCZI-zCYCP-hLiFOYRWq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});